export const nombreTablasMapeadas = {
  receta_medica: "Receta Médica",
  maestro_paciente: "Maestro Paciente",
  tiempo_espera: "Tiempos de Espera",
  fhir: "FHIR",
  deis: "DEIS",
  core: "CoreCL",
  core_minsal: "Core Minsal",
  hl7_guias: "Guías HL7",
  ips: "IPS",
  ipscl: "IPS Cl",
  otras_guias: "Otras Guías",
};

export const nombreColumnasMapeadas = {
  receta_medica: {
    id_computableName: "Computable Name",
    tipo: "Tipo",
    artefacto: "Artefacto",
    dependencia: "Dependencia",
    versionDep: "Proviene de",
    url_dep: "Link de la Dependencia",
    url_version: "Link",
  },
  maestro_paciente: {
    id_computableName: "Computable Name",
    tipo: "Tipo",
    artefacto: "Artefacto",
    dependencia: "Dependencia",
    versionDep: "Proviene de",
    url_dep: "Link de la Dependencia",
    url_version: "Link",
  },
  tiempo_espera: {
    id_computableName: "Computable Name",
    tipo: "Tipo",
    artefacto: "Artefacto",
    dependencia: "Dependencia",
    versionDep: "Proviene de",
    url_dep: "Link de la Dependencia",
    url_version: "Link",
  },
  fhir: {
    url: "Link",
    version: "Version",
    recurso: "Recurso",
  },
  ips: {
    id_computableName: "Computable Name",
    tipo: "Tipo",
    artefacto: "Artefacto",
    dependencia: "Dependencia",
    versionDep: "Proviene de",
    url_dep: "Link de la Dependencia",
    url_version: "Link",
  },
  ipscl: {
    id_computableName: "Computable Name",
    tipo: "Tipo",
    artefacto: "Artefacto",
    dependencia: "Dependencia",
    versionDep: "Proviene de",
    url_dep: "Link de la Dependencia",
    url_version: "Link",
  },
  otras_guias: {
    id_computableName: "Computable Name",
    tipo: "Tipo",
    artefacto: "Artefacto",
    dependencia: "Dependencia",
    versionDep: "Proviene de",
    url_dep: "Link de la Dependencia",
    url_version: "Link",
  },
  hl7_guias: {
    id_computableName: "Computable Name",
    tipo: "Tipo",
    artefacto: "Artefacto",
    dependencia: "Dependencia",
    versionDep: "Proviene de",
    url_dep: "Link de la Dependencia",
    url_version: "Link",
  },
  core: {
    id_computableName: "Computable Name",
    tipo: "Tipo",
    artefacto: "Artefacto",
    dependencia: "Dependencia",
    versionDep: "Proviene de",
    url_dep: "Link de la Dependencia",
    url_version: "Link",
  },
  core_minsal: {
    id_computableName: "Computable Name",
    tipo: "Tipo",
    artefacto: "Artefacto",
    dependencia: "Dependencia",
    versionDep: "Proviene de",
    url_dep: "Link de la Dependencia",
    url_version: "Link",
  },
};

export const tableOrder = [
  "fhir",
  "ips",
  "deis",
  "core",
  "ipscl",
  "core_minsal",
  "hl7_guias",
  "otras_guias",
  "receta_medica",
  "maestro_paciente",
  "tiempo_espera",
];

export const tableGroupTitles = [
  "Primer Grupo de Tablas",
  "Segundo Grupo de Tablas",
  "Tercer Grupo de Tablas",
  "Cuarto Grupo de Tablas",
];

export const tableDescriptions: Record<string, string> = {
  fhir: "Descripción de la tabla 1",
  ips: "Descripción de la tabla 2",
  deis: "Descripción de la tabla 3",
  core: "Descripción de la tabla 4",
  ipscl: "Descripción de la tabla 5",
  core_minsal: "Descripción de la tabla 6",
  hl7_guias: "Descripción de la tabla 7",
  otras_guias: "Descripción de la tabla 8",
  receta_medica: "Descripción de la tabla 9",
  maestro_paciente: "Descripción de la tabla 10",
  tiempo_espera: "Descripción de la tabla 11",
};
