export const nombreTablasMapeadas = {
  receta_medica: "Receta Médica",
  maestro_paciente: "Maestro Paciente",
  tiempo_espera: "Tiempos de Espera",
  fhir: "FHIR",
  deis: "DEIS",
  core: "CoreCL",
  core_minsal: "Core Minsal",
  hl7_guias: "Guías HL7",
  ips: "IPS",
  ipscl: "IPS Cl",
  otras_guias: "Otras Guías",
};

export const nombreColumnasMapeadas = {
  receta_medica: {
    id_computableName: "Computable Name",
    tipo: "Tipo",
    artefacto: "Artefacto",
    dependencia: "Dependencia",
    versionDep: "Proviene de",
    url_dep: "Link de la Dependencia",
    url_version: "Link",
  },
  maestro_paciente: {
    id_computableName: "Computable Name",
    tipo: "Tipo",
    artefacto: "Artefacto",
    dependencia: "Dependencia",
    versionDep: "Proviene de",
    url_dep: "Link de la Dependencia",
    url_version: "Link",
  },
  tiempo_espera: {
    id_computableName: "Computable Name",
    tipo: "Tipo",
    artefacto: "Artefacto",
    dependencia: "Dependencia",
    versionDep: "Proviene de",
    url_dep: "Link de la Dependencia",
    url_version: "Link",
  },
  fhir: {
    url: "Link",
    version: "Version",
    recurso: "Recurso",
  },
  ips: {
    id_computableName: "Computable Name",
    tipo: "Tipo",
    artefacto: "Artefacto",
    dependencia: "Dependencia",
    versionDep: "Proviene de",
    url_dep: "Link de la Dependencia",
    url_version: "Link",
  },
  ipscl: {
    id_computableName: "Computable Name",
    tipo: "Tipo",
    artefacto: "Artefacto",
    dependencia: "Dependencia",
    versionDep: "Proviene de",
    url_dep: "Link de la Dependencia",
    url_version: "Link",
  },
  otras_guias: {
    id_computableName: "Computable Name",
    tipo: "Tipo",
    artefacto: "Artefacto",
    dependencia: "Dependencia",
    versionDep: "Proviene de",
    url_dep: "Link de la Dependencia",
    url_version: "Link",
  },
  hl7_guias: {
    id_computableName: "Computable Name",
    tipo: "Tipo",
    artefacto: "Artefacto",
    dependencia: "Dependencia",
    versionDep: "Proviene de",
    url_dep: "Link de la Dependencia",
    url_version: "Link",
  },
  core: {
    id_computableName: "Computable Name",
    tipo: "Tipo",
    artefacto: "Artefacto",
    dependencia: "Dependencia",
    versionDep: "Proviene de",
    url_dep: "Link de la Dependencia",
    url_version: "Link",
  },
  core_minsal: {
    id_computableName: "Computable Name",
    tipo: "Tipo",
    artefacto: "Artefacto",
    dependencia: "Dependencia",
    versionDep: "Proviene de",
    url_dep: "Link de la Dependencia",
    url_version: "Link",
  },
};
